// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvgpfdmrpnnqjftrmkvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2Z3BmZG1ycG5ucWpmdHJta3ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNjUzNDUsImV4cCI6MjA1Nzg0MTM0NX0.mZ0jZrI2rJZEuJwl8jLWWpy6tINnHO7ThCewWmX1Vac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);